// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: keyword_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Keyword_Layout int32

const (
	Keyword_UNKNOWN Keyword_Layout = 0
	Keyword_QWERTY  Keyword_Layout = 1
	Keyword_QWERTZ  Keyword_Layout = 2
	Keyword_AZERTY  Keyword_Layout = 3
)

// Enum value maps for Keyword_Layout.
var (
	Keyword_Layout_name = map[int32]string{
		0: "UNKNOWN",
		1: "QWERTY",
		2: "QWERTZ",
		3: "AZERTY",
	}
	Keyword_Layout_value = map[string]int32{
		"UNKNOWN": 0,
		"QWERTY":  1,
		"QWERTZ":  2,
		"AZERTY":  3,
	}
)

func (x Keyword_Layout) Enum() *Keyword_Layout {
	p := new(Keyword_Layout)
	*p = x
	return p
}

func (x Keyword_Layout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Keyword_Layout) Descriptor() protoreflect.EnumDescriptor {
	return file_keyword_message_proto_enumTypes[0].Descriptor()
}

func (Keyword_Layout) Type() protoreflect.EnumType {
	return &file_keyword_message_proto_enumTypes[0]
}

func (x Keyword_Layout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Keyword_Layout.Descriptor instead.
func (Keyword_Layout) EnumDescriptor() ([]byte, []int) {
	return file_keyword_message_proto_rawDescGZIP(), []int{0, 0}
}

type Keyword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layout  Keyword_Layout `protobuf:"varint,1,opt,name=layout,proto3,enum=pcbook.Keyword_Layout" json:"layout,omitempty"`
	Backlit bool           `protobuf:"varint,2,opt,name=backlit,proto3" json:"backlit,omitempty"`
}

func (x *Keyword) Reset() {
	*x = Keyword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keyword_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Keyword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keyword) ProtoMessage() {}

func (x *Keyword) ProtoReflect() protoreflect.Message {
	mi := &file_keyword_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keyword.ProtoReflect.Descriptor instead.
func (*Keyword) Descriptor() ([]byte, []int) {
	return file_keyword_message_proto_rawDescGZIP(), []int{0}
}

func (x *Keyword) GetLayout() Keyword_Layout {
	if x != nil {
		return x.Layout
	}
	return Keyword_UNKNOWN
}

func (x *Keyword) GetBacklit() bool {
	if x != nil {
		return x.Backlit
	}
	return false
}

var File_keyword_message_proto protoreflect.FileDescriptor

var file_keyword_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x22,
	0x8e, 0x01, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x6c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x63,
	0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x4c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x63, 0x6b, 0x6c, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x61,
	0x63, 0x6b, 0x6c, 0x69, 0x74, 0x22, 0x39, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x51, 0x57, 0x45, 0x52, 0x54, 0x59, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x51, 0x57, 0x45, 0x52,
	0x54, 0x5a, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x5a, 0x45, 0x52, 0x54, 0x59, 0x10, 0x03,
	0x42, 0x0b, 0x5a, 0x09, 0x70, 0x63, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keyword_message_proto_rawDescOnce sync.Once
	file_keyword_message_proto_rawDescData = file_keyword_message_proto_rawDesc
)

func file_keyword_message_proto_rawDescGZIP() []byte {
	file_keyword_message_proto_rawDescOnce.Do(func() {
		file_keyword_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_keyword_message_proto_rawDescData)
	})
	return file_keyword_message_proto_rawDescData
}

var file_keyword_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keyword_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_keyword_message_proto_goTypes = []interface{}{
	(Keyword_Layout)(0), // 0: pcbook.Keyword.Layout
	(*Keyword)(nil),     // 1: pcbook.Keyword
}
var file_keyword_message_proto_depIdxs = []int32{
	0, // 0: pcbook.Keyword.layout:type_name -> pcbook.Keyword.Layout
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_keyword_message_proto_init() }
func file_keyword_message_proto_init() {
	if File_keyword_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keyword_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Keyword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keyword_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keyword_message_proto_goTypes,
		DependencyIndexes: file_keyword_message_proto_depIdxs,
		EnumInfos:         file_keyword_message_proto_enumTypes,
		MessageInfos:      file_keyword_message_proto_msgTypes,
	}.Build()
	File_keyword_message_proto = out.File
	file_keyword_message_proto_rawDesc = nil
	file_keyword_message_proto_goTypes = nil
	file_keyword_message_proto_depIdxs = nil
}
